version: '1.0'
stages:
  - prepare
  - test
  - integration
  - build
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'codefresh-contrib/spring-boot-2-sample-app'
    revision: master
    git: github
  MyUnitTests:
    title: Compile/Unit test
    stage: test
    image: 'maven:3.5.2-jdk-8-alpine'
    commands:
      - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository package
  Integration:
    title: Integration test
    stage: integration
    image: maven:3.5.2-jdk-8-alpine
    commands:
     - mvn -Dmaven.repo.local=/codefresh/volume/m2_repository verify      
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: spring-boot-2-sample-app
    working_directory: ./
    tag: 'non-multi-stage'
    dockerfile: Dockerfile
  StoreChart:
    title: Storing Helm chart
    stage: deploy
    image: 'codefresh/cfstep-helm:2.12.3'
    environment:
      - ACTION=push
      - CHART_REF=charts/helm-example
  DeployMyChart:
    image: 'codefresh/cfstep-helm:2.12.3'
    title: Deploying Helm chart
    stage: deploy
    environment:
      - CHART_REF=charts/helm-example
      - RELEASE_NAME=my-java-chart-prod
      - KUBE_CONTEXT=sales-demo@FirstKubernetes
      - VALUE_image_pullPolicy=Always
      - VALUE_image_tag='multi-stage'
      - VALUE_replicaCount=3
      - VALUE_image_pullSecret=codefresh-generated-r.cfcr.io-cfcr-default
